
# echo -e "${YC}Download and extract Application${NC}"
# curl -L -o /tmp/frontend.tar.gz https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz &>>$OUTPUT
# mkdir -p /tmp/frontend &>>$OUTPUT
# cd /tmp/frontend
# tar xzf /tmp/frontend.tar.gz &>>$OUTPUT
# status_check
#
# echo -e "${YC}Build frontend code${NC}"
# cd /tmp/frontend
# npm ci &>>$OUTPUT
# npm run build &>>$OUTPUT
# status_check
#
# echo -e "${YC}Update frontend code${NC}"
# rm -rf /usr/share/nginx/html/* &>>$OUTPUT
# cp -r /tmp/frontend/dist/* /usr/share/nginx/html/ &>>$OUTPUT
# status_check
#
# echo -e "${YC}Start nginx service${NC}"
# systemctl enable nginx &>>$OUTPUT
# systemctl restart nginx &>>$OUTPUT
# status_check



- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJS repo files
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -

    - name: Install nginx & NodeJS
      ansible.builtin.dnf:
        name:
          - '@nginx:1.26'
          - nodejs
        state: present

    - name: Update Nginx Config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Download and extract frontend
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz
        dest: /tmp/
        remote_src: yes



